// Section 4 Tax Audit Page
import React, { useState, useEffect, useMemo } from "react";
import {
  Printer,
  Edit3,
  Target,
  Home as HomeIcon,
  AlertOctagon,
  ShieldAlert,
  Bot,
  Sparkles,
  X,
  CheckCircle2,
  Briefcase,
  Landmark,
  Activity,
  GraduationCap,
  Loader2,
  Clock,
  UserCog,
  Wand2,
  ArrowDownCircle,
  Scale,
  FileCheck,
  ArrowRight,
} from "lucide-react";
import { TaxService } from "../services/taxService";
import { AIService } from "../services/aiService";
import { formatIndianCompact } from "../utils/helpers";
import { TABS } from "../config/constants";

// ==========================================
// SUB-COMPONENT: DEDUCTION PROGRESS BAR
// ==========================================
// Visualizes how much of a tax section (like 80C) has been utilized.
// 'pace' prop indicates where the user *should* be at this time of year.
const DeductionBar = ({
  label,
  used,
  limit,
  color = "bg-blue-500",
  pace = 0,
}) => (
  <div className="mb-4 break-inside-avoid">
    <div className="flex justify-between text-xs mb-1">
      <span className="text-slate-300 font-medium print:text-black">
        {label}
      </span>
      <span className="text-slate-400 print:text-gray-600">
        {formatIndianCompact(used)} / {formatIndianCompact(limit)}
      </span>
    </div>
    <div className="h-2 w-full bg-black/40 rounded-full overflow-hidden border border-white/5 relative print:bg-gray-200 print:border-gray-300">
      {/* Actual Progress */}
      <div
        className={`h-full ${color} rounded-full transition-all duration-500 print:bg-slate-800`}
        style={{ width: `${Math.min(100, (used / limit) * 100)}%` }}
      ></div>
      {/* Pace Marker (Expected Progress) */}
      {pace > 0 && (
        <div
          className="absolute top-0 bottom-0 w-0.5 bg-white/50 print:bg-black"
          style={{ left: `${Math.min(100, pace * 100)}%` }}
          title="Recommended Pace"
        ></div>
      )}
    </div>
  </div>
);

// ==========================================
// SUB-COMPONENT: AI ACTION CARD
// ==========================================
// Displays a single tax-saving tip generated by the AI Service.
const TaxActionCard = ({ action, section, savings, deadline }) => (
  <div className="p-4 rounded-2xl bg-gradient-to-br from-emerald-900/40 to-emerald-800/20 border border-emerald-500/30 relative overflow-hidden group hover:border-emerald-500/50 transition-all print:border-gray-300 print:bg-white print:text-black break-inside-avoid">
    <div className="flex justify-between items-start mb-2">
      <span className="bg-emerald-500/20 text-emerald-300 text-[10px] font-bold px-2 py-0.5 rounded-md border border-emerald-500/30 uppercase print:bg-gray-100 print:text-black print:border-gray-300">
        {section}
      </span>
      <div className="flex items-center gap-1 text-[10px] text-emerald-200/70 print:text-slate-500">
        <Clock className="w-3 h-3" /> {deadline}
      </div>
    </div>
    <h4 className="font-bold text-white text-sm mb-1 print:text-black">
      {action}
    </h4>
    <p className="text-xs text-emerald-200/60 print:text-slate-600">
      Potential Savings:{" "}
      <span className="text-emerald-300 font-bold print:text-black">
        {savings}
      </span>
    </p>
  </div>
);

// ==========================================
// SUB-COMPONENT: PROFILE WIZARD MODAL
// ==========================================
// A modal that allows users to manually input tax data (Rent, Loans)
// or accept values "detected" from their transaction history.
const ProfileWizard = ({
  isOpen,
  onClose,
  initialData,
  detectedValues,
  onSave,
}) => {
  const [localProfile, setLocalProfile] = useState(initialData);

  // Sync local state when the modal opens or data updates
  useEffect(() => {
    if (initialData) setLocalProfile(initialData);
  }, [initialData]);

  if (!isOpen) return null;

  // Configuration for the form fields
  const fields = [
    {
      label: "Annual Rent Paid",
      key: "annualRent",
      icon: HomeIcon,
      detected: detectedValues.rent,
    },
    {
      label: "Annual EPF",
      key: "annualEPF",
      icon: Briefcase,
      detected: detectedValues.epf,
    },
    {
      label: "NPS Contribution",
      key: "npsContribution",
      icon: Landmark,
      detected: detectedValues.nps,
    },
    {
      label: "Health Ins. (Self)",
      key: "healthInsuranceSelf",
      icon: Activity,
      detected: detectedValues.health,
    },
    {
      label: "Health Ins. (Parents)",
      key: "healthInsuranceParents",
      icon: Activity,
      detected: 0,
    },
    {
      label: "Home Loan Interest",
      key: "homeLoanInterest",
      icon: HomeIcon,
      detected: 0,
    },
    {
      label: "Edu Loan Interest",
      key: "educationLoanInterest",
      icon: GraduationCap,
      detected: 0,
    },
  ];

  return (
    <div className="fixed inset-0 bg-black/80 z-[60] flex items-center justify-center p-4 animate-in fade-in duration-200 print:hidden">
      <div className="bg-[#0f0c29] w-full max-w-sm p-6 rounded-[2rem] border border-white/10 shadow-2xl relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 bg-white/5 hover:bg-white/10 rounded-full text-slate-400 hover:text-white transition-colors"
        >
          <X className="w-4 h-4" />
        </button>
        <h3 className="text-xl font-bold text-white mb-6">
          Update Tax Profile
        </h3>

        <div className="space-y-4 max-h-[60vh] overflow-y-auto pr-2 custom-scrollbar">
          {/* Business Income Toggle (affects Regime selection logic) */}
          <div
            className="flex items-center gap-3 p-4 bg-white/5 rounded-2xl border border-white/10 cursor-pointer hover:bg-white/10 transition-colors"
            onClick={() =>
              setLocalProfile({
                ...localProfile,
                isBusiness: !localProfile.isBusiness,
              })
            }
          >
            <div
              className={`w-5 h-5 rounded-md border flex items-center justify-center ${localProfile.isBusiness ? "bg-blue-500 border-blue-500" : "border-slate-500"}`}
            >
              {localProfile.isBusiness && (
                <CheckCircle2 className="w-3.5 h-3.5 text-white" />
              )}
            </div>
            <div className="flex flex-col">
              <span className="text-sm font-medium text-white">
                I have Business Income
              </span>
              <span className="text-[10px] text-slate-400">
                Select if you earn apart from Salary
              </span>
            </div>
          </div>

          {/* Dynamic Field Rendering */}
          {fields.map((field) => (
            <div key={field.key} className="space-y-2">
              <div className="flex justify-between items-center">
                <label className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                  <field.icon className="w-3 h-3" /> {field.label}
                </label>
                {/* "Use Detected" Button: Only appears if algorithm found something */}
                {field.detected > 0 && (
                  <button
                    onClick={() =>
                      setLocalProfile({
                        ...localProfile,
                        [field.key]: field.detected,
                      })
                    }
                    className="text-[9px] font-bold text-cyan-300 bg-cyan-500/10 px-2 py-0.5 rounded flex items-center gap-1 hover:bg-cyan-500/20"
                  >
                    <ArrowDownCircle className="w-3 h-3" /> Use Detected ₹
                    {formatIndianCompact(field.detected)}
                  </button>
                )}
              </div>
              <input
                type="number"
                value={localProfile[field.key]}
                onChange={(e) =>
                  setLocalProfile({
                    ...localProfile,
                    [field.key]: e.target.value,
                  })
                }
                className="w-full px-4 py-3 bg-black/40 border border-white/10 rounded-xl text-white outline-none focus:border-blue-500/50 transition-colors placeholder:text-slate-600"
                placeholder={
                  field.detected > 0 ? `Detected: ${field.detected}` : "0"
                }
              />
            </div>
          ))}
        </div>

        <div className="pt-6 mt-2 border-t border-white/5">
          <button
            onClick={() => {
              onSave(localProfile);
              onClose();
            }}
            className="w-full bg-blue-600 hover:bg-blue-500 text-white py-4 rounded-xl font-bold shadow-lg shadow-blue-900/20 transition-all"
          >
            Save Profile
          </button>
        </div>
      </div>
    </div>
  );
};

// ==========================================
// MAIN COMPONENT: AUDIT PAGE
// ==========================================
const AuditPage = ({
  transactions,
  wealthItems,
  taxProfile,
  onUpdateProfile,
  showToast,
  settings,
  setActiveTab,
}) => {
  // --- UI State ---
  const [adviceCards, setAdviceCards] = useState([]); // Stores AI Suggestions
  const [loading, setLoading] = useState(false); // Loading state for AI
  const [showWizard, setShowWizard] = useState(false); // Modal visibility

  // --- 1. CORE CALCULATION LOGIC ---
  // Calls the TaxService to compute liability under Old vs New Regime
  const data = useMemo(() => {
    const rawData = TaxService.calculate(
      transactions,
      taxProfile,
      wealthItems,
      settings,
    );

    // Logic for Recommendation: Identify which regime is cheaper
    const isNewCheaper = rawData.taxNew <= rawData.taxOld;

    return {
      ...rawData,
      isNewCheaper,
      recommendedTax: Math.min(rawData.taxNew, rawData.taxOld),
    };
  }, [transactions, taxProfile, wealthItems, settings]);

  // --- 2. SMART AUTO-DETECTION ENGINE ---
  // Scans transaction descriptions for keywords (rent, lic, nps) to pre-fill form data.
  const detectedValues = useMemo(() => {
    const result = { rent: 0, epf: 0, health: 0, nps: 0 };
    transactions.forEach((t) => {
      const desc = t.description.toLowerCase();
      const val = parseFloat(t.amount);
      if (t.type === "expense") {
        if (desc.includes("rent") && val > 1000) result.rent += val;
        if (
          desc.includes("ppf") ||
          desc.includes("lic") ||
          desc.includes("elss")
        )
          result.epf += val;
        if (
          (desc.includes("health") || desc.includes("mediclaim")) &&
          !desc.includes("lic")
        )
          result.health += val;
        if (desc.includes("nps")) result.nps += val;
      }
    });
    return result;
  }, [transactions]);

  // --- 3. USER PERSONA CLASSIFICATION ---
  // Determines if user is Salaried, Freelancer, or High Net Worth based on income sources.
  const userPersona = useMemo(() => {
    const tags = [];
    const hasSalary = data.heads.salary > 0;
    const hasBusiness = taxProfile.isBusiness;

    if (hasSalary && hasBusiness) tags.push("Hybrid (Job + Business)");
    else if (hasBusiness) tags.push("Freelancer");
    else tags.push("Salaried Employee");

    if (data.sources.total > 1500000) tags.push("High Net Worth");
    else if (data.sources.total < 500000) tags.push("Tax Exempt");

    return tags;
  }, [taxProfile, data]);

  // --- 4. INTEGRITY SCORE (GAMIFICATION) ---
  // Calculates a "Trust Score" based on how many transactions are verified (not manual).
  const integrityScore = useMemo(() => {
    if (transactions.length === 0) return 100;
    const verifiedCount = transactions.filter(
      (t) => t.verificationStatus === "verified" || t.confidence > 0,
    ).length;
    return Math.round((verifiedCount / transactions.length) * 100);
  }, [transactions]);

  let integrityColor = "text-emerald-400";
  let integrityLabel = "Audit Ready";
  if (integrityScore < 50) {
    integrityColor = "text-rose-400";
    integrityLabel = "High Audit Risk";
  } else if (integrityScore < 80) {
    integrityColor = "text-amber-400";
    integrityLabel = "Verification Needed";
  }

  // --- 5. AI ADVICE HANDLER ---
  // Sends the calculated tax data to the AI Service to get personalized tips.
  const getAdvice = async () => {
    setLoading(true);
    try {
      // Build context for the AI
      const contextData = JSON.stringify({
        persona: userPersona.join(", "),
        regime: data.taxNew < data.taxOld ? "New Regime" : "Old Regime",
        income: {
          total: data.sources.total,
          salary: data.heads.salary,
          business: data.heads.business,
        },
        taxLiability: Math.min(data.taxNew, data.taxOld),
        unused80C: data.deductions.c80.limit - data.deductions.c80.used,
      });

      // Prompt Engineering
      const systemPrompt = `
                Act as an Indian Tax CA. Generate 3 specific tax-saving actions for this persona.
                Output JSON array: [{ "action": "...", "section": "...", "savings": "...", "deadline": "..." }]
            `;

      // Call Service
      const result = await AIService.askForJSON(systemPrompt, contextData);
      setAdviceCards(result);
    } catch (e) {
      console.error(e);
      showToast("AI Service Unavailable", "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 pb-4 animate-in fade-in print:pb-0 print:text-black print:bg-white">
      {/* --- HEADER SECTION --- */}
      <div className="flex justify-between items-start print:hidden">
        <div>
          <h2 className="text-2xl font-bold text-white mb-2">Tax Audit</h2>
          {/* Tags Badge */}
          <div className="flex flex-wrap gap-2">
            <span className="text-[10px] font-bold px-2 py-1 rounded-md bg-white/5 text-slate-400 border border-white/10 flex items-center gap-1">
              <Wand2 className="w-3 h-3" /> Analyzed {transactions.length}{" "}
              Transactions
            </span>
            {userPersona.map((tag) => (
              <span
                key={tag}
                className="text-[10px] font-bold px-2 py-1 rounded-md bg-blue-500/10 text-blue-200 border border-blue-500/20 flex items-center gap-1"
              >
                <UserCog className="w-3 h-3" /> {tag}
              </span>
            ))}
          </div>
        </div>
        {/* Header Actions: Print & Edit Profile */}
        <div className="flex gap-2">
          <button
            onClick={() => window.print()}
            className="p-2 bg-white/10 rounded-full hover:bg-white/20 transition-colors text-slate-300"
          >
            <Printer className="w-5 h-5" />
          </button>
          <button
            onClick={() => setShowWizard(true)}
            className="p-2 bg-white/10 rounded-full hover:bg-white/20 transition-colors text-white"
          >
            <Edit3 className="w-5 h-5" />
          </button>
        </div>
      </div>

      {/* --- PRINT ONLY HEADER --- */}
      {/* This only appears when user presses Ctrl+P */}
      <div className="hidden print:block text-center mb-8 border-b-2 border-black pb-4">
        <h1 className="text-3xl font-bold text-black uppercase tracking-wider">
          Tax Audit Report
        </h1>
        <div className="flex justify-between mt-4 text-sm text-gray-600">
          <p>
            <strong>Name:</strong> {settings?.name || "User"}
          </p>
          <p>
            <strong>FY:</strong> {data.fiscalYear}
          </p>
          <p>
            <strong>Date:</strong> {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>

      {/* --- CTA CARD: GO TO FILING --- */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-600 p-1 rounded-[2rem] shadow-2xl print:hidden">
        <div className="bg-slate-900/50 backdrop-blur-md rounded-[1.8rem] p-6 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center text-white shadow-lg shadow-blue-500/40">
              <FileCheck className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">Ready to File?</h3>
              <p className="text-xs text-blue-200">
                Your estimated tax is{" "}
                <span className="font-bold text-white">
                  ₹{Math.min(data.taxNew, data.taxOld).toLocaleString()}
                </span>
                . File your self-declaration now.
              </p>
            </div>
          </div>
          <button
            onClick={() => setActiveTab(TABS.ITR)}
            className="w-full md:w-auto px-6 py-3 bg-white text-blue-900 font-bold rounded-xl hover:bg-blue-50 transition-colors flex items-center justify-center gap-2 shadow-lg"
          >
            File ITR Now <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* --- TAX OVERVIEW CARD (OLD vs NEW) --- */}
      <div className="bg-gradient-to-br from-indigo-900/40 to-blue-900/40 backdrop-blur-xl p-6 rounded-[2rem] border border-white/10 shadow-2xl relative overflow-hidden print:border print:border-gray-300 print:shadow-none print:bg-none print:text-black break-inside-avoid">
        <div className="relative z-10 grid grid-cols-2 gap-6">
          <div>
            <p className="text-xs text-slate-400 font-bold uppercase tracking-wider mb-1 print:text-gray-600">
              Taxable Income
            </p>
            <h3 className="text-2xl font-bold text-white print:text-black">
              ₹{data.taxableNew.toLocaleString()}
            </h3>
            <p className="text-[10px] text-indigo-300 mt-1 print:text-gray-500">
              FY {data.fiscalYear}
            </p>
          </div>
          <div className="text-right">
            <p className="text-xs text-slate-400 font-bold uppercase tracking-wider mb-1 print:text-gray-600">
              Recommended
            </p>
            <div
              className={`inline-block px-3 py-1 rounded-lg text-sm font-bold ${data.taxNew < data.taxOld ? "bg-emerald-500/20 text-emerald-300" : "bg-amber-500/20 text-amber-300"}`}
            >
              {data.taxNew < data.taxOld ? "NEW REGIME" : "OLD REGIME"}
            </div>
            <p className="text-[10px] text-slate-400 mt-1 print:text-gray-500">
              Est. Liability: ₹
              {Math.min(data.taxNew, data.taxOld).toLocaleString()}
            </p>
            {/* Optional: Add a "Tax Free" badge for income <= 12.75L in New Regime */}
            {data.taxNew === 0 &&
              data.heads.salary > 0 &&
              data.sources.total <= 1275000 && (
                <span className="block text-[10px] text-emerald-400 font-bold">
                  ✨ TAX FREE LIMIT
                </span>
              )}
          </div>
        </div>
      </div>

      {/* --- AI STRATEGIST SECTION --- */}
      <div className="bg-[#0f172a] p-6 rounded-[2rem] border border-white/10 relative overflow-hidden shadow-xl print:hidden">
        {/* Background Decoration */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 blur-[80px] rounded-full pointer-events-none"></div>

        <div className="flex justify-between items-start mb-6 relative z-10">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Bot className="w-5 h-5 text-emerald-400" />
              <h3 className="font-bold text-white text-lg tracking-tight">
                AI Consultant
              </h3>
            </div>
            <p className="text-xs text-slate-400">
              Tailored for {userPersona[0]}
            </p>
          </div>
          <button
            onClick={getAdvice}
            disabled={loading}
            className="bg-emerald-600 hover:bg-emerald-500 text-white px-4 py-2 rounded-xl text-xs font-bold transition-all shadow-lg shadow-emerald-900/20 flex items-center gap-2"
          >
            {loading ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4 text-yellow-300" />
            )}
            {loading ? "Analyzing..." : "Identify Savings"}
          </button>
        </div>

        <div className="relative z-10 min-h-[50px]">
          {/* Empty State */}
          {!loading && adviceCards.length === 0 && (
            <div className="text-center py-6 text-slate-500 text-xs border border-dashed border-slate-700 rounded-xl">
              Tap 'Identify Savings' to generate a plan specific to your
              profession.
            </div>
          )}
          {/* Result Cards */}
          {adviceCards.length > 0 && (
            <div className="grid gap-3 animate-in slide-in-from-bottom-4">
              {adviceCards.map((card, idx) => (
                <TaxActionCard key={idx} {...card} />
              ))}
            </div>
          )}
        </div>
      </div>

      {/* --- 5 HEADS OF INCOME BREAKDOWN --- */}
      <div className="bg-white/5 p-6 rounded-[2rem] border border-white/10 print:border-gray-300 print:bg-white print:text-black break-inside-avoid">
        <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2 print:text-black">
          <Scale className="w-4 h-4" /> 5 Heads of Income
        </h3>
        <div className="space-y-3">
          <div className="flex justify-between text-sm">
            <span className="text-slate-300 print:text-gray-700">
              1. Salary
            </span>
            <span className="text-white font-medium print:text-black">
              ₹{data.heads.salary.toLocaleString()}
            </span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-300 print:text-gray-700">
              2. House Property
            </span>
            <span className="text-white font-medium print:text-black">
              ₹{data.heads.houseProperty.toLocaleString()}
            </span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-300 print:text-gray-700">
              3. Business / Profession
            </span>
            <span className="text-white font-medium print:text-black">
              ₹{data.heads.business.toLocaleString()}
            </span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-300 print:text-gray-700">
              4. Capital Gains
            </span>
            <span className="text-yellow-400 font-medium print:text-black">
              ₹{data.heads.capitalGains.toLocaleString()}*
            </span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-300 print:text-gray-700">
              5. Other Sources
            </span>
            <span className="text-white font-medium print:text-black">
              ₹{data.heads.other.toLocaleString()}
            </span>
          </div>
        </div>
      </div>

      {/* --- DEDUCTIONS ANALYSIS (OLD REGIME) --- */}
      <div className="bg-white/5 p-6 rounded-[2rem] border border-white/10 print:border-gray-300 print:bg-white print:text-black break-inside-avoid">
        <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2 print:text-black">
          <Target className="w-4 h-4" /> Deductions (Old Regime)
        </h3>
        <DeductionBar
          label="80C Investments"
          used={data.deductions.c80.used}
          limit={150000}
          color="bg-cyan-500"
          pace={data.mode === "PLANNING" ? data.deductions.c80.pace : 0}
        />
        <DeductionBar
          label="80D Health Ins."
          used={data.deductions.d80.used}
          limit={75000}
          color="bg-pink-500"
        />
        <DeductionBar
          label="NPS (80CCD 1B)"
          used={data.deductions.nps.used}
          limit={50000}
          color="bg-purple-500"
        />

        {/* Leakage Alert: Shows if you can still save more tax */}
        {data.missedSavings > 0 && (
          <div className="mt-4 p-3 bg-red-500/10 border border-red-500/20 rounded-xl flex items-center gap-3 print:border-gray-300 print:bg-gray-50">
            <AlertOctagon className="w-5 h-5 text-red-400 print:text-red-600" />
            <div>
              <p className="text-xs text-red-200 font-bold print:text-black">
                Leakage Detected
              </p>
              <p className="text-[10px] text-red-300/70 print:text-gray-600">
                You are missing out on ~₹
                {Math.round(data.missedSavings).toLocaleString()} in potential
                tax savings.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* --- INTEGRITY SCORE --- */}
      <div className="p-4 rounded-[1.5rem] bg-white/5 border border-white/10 flex flex-col gap-3 print:border-gray-300 print:bg-white print:text-black break-inside-avoid">
        <div className="flex justify-between items-start">
          <div className="flex items-start gap-3">
            <ShieldAlert
              className={`w-5 h-5 ${integrityScore < 80 ? "text-amber-500" : "text-emerald-500"} shrink-0 mt-0.5`}
            />
            <div>
              <h4 className="text-sm font-bold text-white mb-1 print:text-black">
                Data Integrity Score
              </h4>
              <p className="text-xs text-slate-400 leading-relaxed print:text-gray-600">
                Based on verified vs. manual entries.
              </p>
            </div>
          </div>
          <div className="text-right">
            <h3
              className={`text-xl font-bold ${integrityColor} print:text-black`}
            >
              {integrityScore}%
            </h3>
            <p className="text-[10px] text-slate-500 uppercase font-bold tracking-wider">
              {integrityLabel}
            </p>
          </div>
        </div>

        <div className="h-1.5 w-full bg-black/40 rounded-full overflow-hidden flex print:bg-gray-200">
          <div
            className="h-full bg-emerald-500 print:bg-black"
            style={{ width: `${integrityScore}%` }}
          ></div>
        </div>

        {integrityScore < 80 && (
          <p className="text-[10px] text-rose-300 bg-rose-500/10 p-2 rounded-lg border border-rose-500/20 print:border-gray-300 print:bg-white print:text-black">
            <strong>Note:</strong> Low verification score. Ensure transactions
            are backed by OCR or bank statements before filing.
          </p>
        )}
      </div>

      {/* --- FOOTER DISCLAIMER --- */}
      <div className="text-center pt-8 pb-8 print:pb-4 border-t border-white/5 print:border-black mt-8">
        <p className="text-[10px] text-slate-600 print:text-gray-500">
          <strong>DISCLAIMER:</strong> This report is a computer-generated
          estimate based on user-provided financial data.
        </p>
      </div>

      {/* --- MODALS --- */}
      <ProfileWizard
        isOpen={showWizard}
        onClose={() => setShowWizard(false)}
        initialData={taxProfile}
        detectedValues={detectedValues}
        onSave={onUpdateProfile}
      />
    </div>
  );
};

export default AuditPage;
