# Generated by Django 6.0.2 on 2026-02-15 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(default='2025-26', max_length=10)),
                ('regime', models.CharField(choices=[('old', 'Old'), ('new', 'New')], default='new', max_length=5)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('house_property_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('business_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_gains', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('section_80c', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('section_80d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('section_80e', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('section_80g', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nps_80ccd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_filed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
