# Generated by Django 6.0.2 on 2026-02-20 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business', models.BooleanField(default=False)),
                ('annual_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('annual_epf', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('nps_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('health_insurance_self', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('health_insurance_parents', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('education_loan_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
