# Generated by Django 6.0.2 on 2026-02-21 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_taxprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_regime', models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('house_property', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital_gains', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80c', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80e', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('section_80g', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nps_80ccd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
