# Generated by Django 6.0.2 on 2026-02-15 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_wealthitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxdeclaration',
            options={'ordering': ['-financial_year', '-created_at'], 'verbose_name': 'Tax Declaration'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Transaction'},
        ),
        migrations.AlterModelOptions(
            name='wealthitem',
            options={'ordering': ['-amount'], 'verbose_name': 'Wealth Item'},
        ),
        migrations.RenameField(
            model_name='taxdeclaration',
            old_name='interest_income',
            new_name='fd_interest',
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='filed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='savings_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='standard_deduction',
            field=models.DecimalField(decimal_places=2, default=75000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='total_tax_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ocr', 'OCR Scan'), ('pdf', 'PDF Parser')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='wealthitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wealthitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='regime',
            field=models.CharField(choices=[('old', 'Old'), ('new', 'New')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='confidence',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_business', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('onboarding_step', models.CharField(choices=[('profile', 'Profile Set'), ('budget', 'Budget Set'), ('complete', 'Completed')], default='profile', max_length=20)),
                ('annual_rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_epf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nps_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('health_insurance_self', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('health_insurance_parents', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('education_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
