# Generated by Django 6.0.2 on 2026-02-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_itrdata_delete_itrprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itrdata',
            name='deductions_data',
        ),
        migrations.RemoveField(
            model_name='itrdata',
            name='tax_regime',
        ),
    ]
