# Generated by Django 6.0.2 on 2026-02-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_transaction_user_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
