# Generated by Django 6.0.2 on 2026-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_itrdata_deductions_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itrdata',
            options={'verbose_name': 'ITR Data', 'verbose_name_plural': 'ITR Data Profiles'},
        ),
        migrations.AddField(
            model_name='itrdata',
            name='deductions_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itrdata',
            name='tax_regime',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=10),
        ),
    ]
